// react-app/src/App.js
import { useEffect, useRef, useState } from "react";

function App() {
  // State

  const [todos, setTodos] = useState([]);

  // Binding
  const todoText = useRef();

  // Events

  function addTodo(e) {
    e.preventDefault();
    const updatedList = [...todos, todoText.current.value];
    setTodos(updatedList);
    localStorage.setItem("todos", JSON.stringify(updatedList));
  }

  // Side Effects (lifecycle hooks)

  useEffect(() => {
    const storageTodos = localStorage.getItem("todos");
    setTodos(storageTodos ? JSON.parse(storageTodos) : []);
  }, []);

  return (
    <>
      <ul>
        {todos.map((todo, index) => (
          <li key={index}>{todo}</li>
        ))}
      </ul>
      <form onSubmit={addTodo}>
        <input type="text" placeholder="Digite sua tarefa" ref={todoText} />
        <button type="submit">Adicionar Tarefa</button>
      </form>
    </>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Lista de tarefas - Angular';

  // State
  todos: string[] = [];
  todoText: string = '';

  // Lifecycle
  ngOnInit(): void {
   this.todos = JSON.parse(localStorage.getItem("todos") as string) || [];
  };

  // Events
  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }
}

<ul>
  <li *ngFor="let todo of todos">{{ todo }}</li>
</ul>

<form (ngSubmit)="addTodo()">
  <input
    type="text"
    name="todotext"
    placeholder="Digite sua tarefa"
    [(ngModel)]="todoText"
  />
  <button type="submit">Adicionar Tarefa</button>
</form>
